name: Yug Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./yugasgn2
        run: npm install

      - name: Run tests
        working-directory: ./yugasgn2
        run: npm test

      - name: Build project
        working-directory: ./yugasgn2
        run: npm run build

